const jobs = [
{
    id:1,
    title:"Frontend Developer",
    company:"Google",
    location:"Hyderabad",
    salary:"₹12 LPA",
    type:"Full Time",
    experience:"0-2 Years",
    skills:["HTML","CSS","JavaScript","React"],
    featured:true,
    rating : 4.8
},
{
    id:2,
    title:"Backend Developer",
    company:"Microsoft",
    location:"Bengaluru",
    salary:"₹15 LPA",
    type:"Full Time",
    experience:"1-3 Years",
    skills:["Node.js","Express","MongoDB"],
    featured:true,
    rating : 4.6
},
{
    id:3,
    title:"Software Engineer",
    company:"Amazon",
    location:"Hyderabad",
    salary:"₹18 LPA",
    type:"Full Time",
    experience:"0-2 Years",
    skills:["Java","Spring Boot","AWS"],
    featured:false,
    rating : 4.7
},
{
    id:4,
    title:"Python Developer",
    company:"Infosys",
    location:"Pune",
    salary:"₹8 LPA",
    type:"Full Time",
    experience:"0-1 Year",
    skills:["Python","Django","MySQL"],
    featured:true,
    rating : 4.5
},
{
    id:5,
    title:"UI UX Designer",
    company:"Adobe",
    location:"Remote",
    salary:"₹10 LPA",
    type:"Remote",
    experience:"1-3 Years",
    skills:["Figma","Adobe XD","Photoshop"],
    featured:false,
    rating : 4.9
},
{
    id:6,
    title:"Cloud Engineer",
    company:"IBM",
    location:"Chennai",
    salary:"₹13 LPA",
    type:"Hybrid",
    experience:"2-4 Years",
    skills:["Azure","Docker","Kubernetes"],
    featured:true,
    rating : 4.4
},
{
    id:7,
    title:"AI Engineer",
    company:"OpenAI",
    location:"Remote",
    salary:"₹25 LPA",
    type:"Remote",
    experience:"2-5 Years",
    skills:["Python","Machine Learning","TensorFlow"],
    featured:true,
    rating : 4.8
},
{
    id:8,
    title:"Full Stack Developer",
    company:"TCS",
    location:"Hyderabad",
    salary:"₹9 LPA",
    type:"Full Time",
    experience:"0-2 Years",
    skills:["HTML","CSS","JavaScript","Node.js"],
    featured:false, 
    rating : 4.3
},
{
    id:9,
    title:"DevOps Engineer",
    company:"Accenture",
    location:"Bengaluru",
    salary:"₹14 LPA",
    type:"Hybrid",
    experience:"2-4 Years",
    skills:["Docker","Jenkins","AWS"],
    featured:false,
    rating : 4.6
},
{
    id:10,
    title:"Data Analyst",
    company:"Deloitte",
    location:"Mumbai",
    salary:"₹9 LPA",
    type:"Full Time",
    experience:"0-2 Years",
    skills:["SQL","Power BI","Excel"],
    featured:true,
    rating : 4.7
}
];